Repository ibrahimcesar/react-lite-youtube-embed, pull requests merged in 2021-09, with the labels that each got.

#25 🐛 fix: type error, announce order and should be optionional
  README.md
Labels: bug, documentation

#26 🔖 upgrade: several upgrades in packages to latest version
  README.md
  demo/package-lock.json
  demo/package.json
  demo/pages/index.js
  dist/LiteYouTubeEmbed.css
  dist/index.d.ts
  dist/index.es.jsx
  dist/index.es.jsx.map
  dist/index.jsx
  dist/index.jsx.map
  package-lock.json
  package.json
  src/lib/LiteYouTubeEmbed.css
  src/lib/index.tsx
Labels: enhancement

#29 🎨 feat: support for webp format
  demo/package-lock.json
  demo/package.json
  demo/pages/index.js
  dist/index.d.ts
  dist/index.es.jsx
  dist/index.es.jsx.map
  dist/index.jsx
  dist/index.jsx.map
  package.json
  src/lib/index.tsx
Labels: enhancement

#31 Fix typo on iframeClass
  README.md
Labels: documentation
